### ISSUE TITLE
64 bit sample output

### ISSUE THREAD

**Issue by majiang** [MersenneTwister-Lab/SFMT#4]
It is convenient to have sample output for 64 bit also.

**Comment by MSaito** [comment]
Maybe it's nice. But it has low priority.Wait without expectation.

**Comment by MSaito** [comment]
sample output files for 64 bit added.

**Comment by majiang** [comment]
checked that it's 284f4f55. Thanks!

**Comment by majiang** [comment]
Also, you can close the issue on pushing a commit with commit message "close #4" etc.
